language: node_js
node_js:
  - "8"
services:
  - postgresql

# before_script:
#   - npm install
#   - psql -c 'create database travis_ci_test;' -U postgres
# - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
# - chmod +x ./cc-test-reporter
#   - ./cc-test-reporter before-build
# script:
#   - nyc --reporter=lcov yarn run unit
# after_script:
#   - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success: 
  - npm run coverage